{% set name = "lonboard" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lonboard-{{ version }}.tar.gz
  sha256: 12164ce778fb1fd179b18da9841a2994e8477971b63a11b42bb147d9922b7074

build:
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

  number: 0

requirements:
  build:
    - nodejs
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - anywidget >=0.9.0
    - arro3-compute >=0.4.1
    - arro3-core >=0.4.1
    - arro3-io >=0.4.1
    - ipywidgets >=7.6.0
    - numpy >=1.14
    - pyproj >=3.3
    - traitlets >=5.10

test:
  imports:
    - lonboard
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/developmentseed/lonboard
  summary: Python library for fast, interactive geospatial vector data visualization in Jupyter.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
    - kylebarron
