{% set name = "lonboard" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/developmentseed/lonboard/archive/refs/tags/v{{ version }}.zip
  sha256: 2f952777f5d263383220949854be3dfd8201fd731e36fdc23d04fae3abc7a8a9

build:
  noarch: python
  script: 
    - npm install
    - npm run build
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - {{ PYTHON }} -m pip install -U build
    - {{ PYTHON }} -m build
  number: 1

requirements:
  build:
    - nodejs
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - anywidget >=0.6.3,<0.7.0
    - pyarrow >=13.0.0,<14.0.0
    - geopandas >=0.13
    - palettable >=3.3.3,<4.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - shapely >=2.0.0,<3.0.0

test:
  imports:
    - lonboard
  commands:
    - pip check
  requires:
    - pip

outputs:
  - name: lonboard
    files:
      - static/index.js
      - static/index.css

about:
  home: https://github.com/developmentseed/lonboard
  summary: Python library for fast, interactive geospatial vector data visualization in Jupyter.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - giswqs
